name: Run Integration and E2E tests
# TODO add test.sh and sonarqube integration
on:
  - push
jobs:
  build:
    name: Install Node, Build, and Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Verify Chrome installation
        run: google-chrome-stable --version

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "PORT=4201" > server/.env
          echo "APP_PORT=4200" >> server/.env

      - name: Start Angular server
        run: npm run prod &

      - name: Wait for Angular server to start
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:4200; do
            echo 'Waiting for Angular server...'
            sleep 5
          done
          echo 'Angular server is up and running!'
          sleep 20 # give the server some time to fully start up

      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: 'chrome:headless --disable-search-engine-choice-screen --no-sandbox --window-size=1280,1024 tests/e2e/run'
