name: Run TestCafe tests
on:
  - push
jobs:
  build:
    name: Install Node and launch TestCafe tests in Chrome
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Start Angular server
        run: npm run start -- --watch --poll=1000 &

      - name: Wait for Angular server to start
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:4200; do
            echo 'Waiting for Angular server...'
            sleep 5
          done

      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: |
            chrome '--window-size=1280,1024' tests/e2e/run
